services:
  notification-database:
    image: mysql:8.0
    container_name: notification-database
    volumes:
      - notification-database-volume:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
  notification-rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    hostname: notification-rabbitmq
    volumes:
      - notification-rabbitmq-volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

volumes:
  notification-rabbitmq-volume:
    driver: local
  notification-database-volume:
    driver: local

networks:
  notification-rabbitmq-network:
    name: notification-rabbitmq-network
    driver: bridge