services:
  notification-database:
    image: mysql:8.0
    container_name: notification-database
    volumes:
      - notification-database-volume:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
  notification-microservice:
    image: notification-microservice:latest
    container_name: notification-microservice
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - notification-database
    environment:
      NEW_UID: "${USER_ID}"

volumes:
  notification-database-volume:
    driver: local

networks:
  notification-rabbitmq-network:
    name: notification-rabbitmq-network
    driver: bridge